Update Sky Atlas for Oct 14 poll
makerdao/next-gen-atlas pull request #40
Opened 2024-10-12 17:34 UTC by MakerJanSky

WIP  

TODO:
- [ ] Add Sections from Early Bird Bonus and on
- [ ] Review Formatting
- [ ] Obtain AA approval

2024-10-14 12:26 UTC, 0xldr commented on Sky Atlas/Sky Atlas.html
> +              continue to target 50% of the estimated net protocol income.• splitter.bump: 25,000 DAI• splitter.hop: 15,649 seconds• 70% of
bump and hump are vow parameters.
```suggestion
          <td>The current Surplus Buffer Splitter parameters are:• vow.hump: 60m (Threshold of Surplus buffer for Splitter to activate)•
              Estimated Net protocol Income: 100,765,523• 50% of estimated net protocol income is sent to Splitter: 50,382,762 (for SBE and 
              Seal Module, remaining 50% is accumulated in Surplus Buffer). This value must be regularly updated through an executive vote to 
              continue to target 50% of the estimated net protocol income.• vow.bump: 25,000 DAI• splitter.hop: 15,649 seconds• 70% of 
```

2024-10-14 14:03 UTC, 0xldr commented on Sky Atlas/Sky Atlas.html
> +          <td>Total Voting Power Delegated  - Element Annotation</td>
```suggestion
          <td>Total Voting Power Delegated - Element Annotation</td>
```

2024-10-14 14:22 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            The number of Prime Delegate slots is specified in  <dfn>A.1.5
```suggestion
            The number of Prime Delegate slots is specified in <dfn>A.1.5
```

2024-10-14 15:03 UTC, blimpa requested changes
dfn tags

2024-10-14 15:03 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            Budget And Participation Requirements - Payout Limitations For ADs Triggering Atlas Edit Weekly Cycle Proposals.</td>
```suggestion
            Budget And Participation Requirements - Payout Limitations For ADs Triggering Atlas Edit Weekly Cycle Proposals</dfn>.</td>
```

2024-10-14 15:03 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            worth of the budget specified in A.1.5 - Aligned Delegates - Budget And Participation Requirements - Budget Amount For
```suggestion
            worth of the budget specified in <dfn>A.1.5 - Aligned Delegates - Budget And Participation Requirements - Budget Amount For 
```

2024-10-14 15:03 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            Prime Delegate Slots until the Proposal has been voted on or rejected by the Governance Facilitators for misalignment.</td>
```suggestion
            Prime Delegate Slots</dfn> until the Proposal has been voted on or rejected by the Governance Facilitators for misalignment.</td>
```

2024-10-14 15:03 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +          <td>If an AD has triggered an Atlas Edit Weekly Cycle Proposal pursuant to A.1.11 - Weekly Governance Cycle - Atlas Edit
```suggestion
          <td>If an AD has triggered an Atlas Edit Weekly Cycle Proposal pursuant to <dfn>A.1.11 - Weekly Governance Cycle - Atlas Edit 
```

2024-10-14 15:03 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            Weekly Cycle - Triggering Requirement, no payouts may be made that would reduce their AD Buffer below one (1) month’s
```suggestion
            Weekly Cycle - Triggering Requirement</dfn>, no payouts may be made that would reduce their AD Buffer below one (1) month’s 
```

2024-10-17 16:29 UTC, 0xldr approved these changes

2024-10-17 16:29 UTC, merged