Adding Weekly Atlas Edit Proposal - Week of 2024-10-28
makerdao/next-gen-atlas pull request #42
Opened 2024-10-28 13:11 UTC by MakerJanSky

2024-10-28 14:10 UTC, blimpa requested changes

2024-10-28 14:10 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            tokenomics or anything else.<br> The 3 poll options are as follows:<br> Option 1:<br> Keep the Sky brand as
I would suggest adding `&emsp;` or some other spacing entity before each line belonging to the description of the options for improved clarity, e.g.:

`&emsp; Keep the Sky brand as` 

Which should look like this:

&emsp; Keep the Sky Brand

2024-10-28 14:10 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            depending on what outcome is chosen for the Sky brand, the current SKY token may be renamed (e.g. to OLD_SKY), and a new
```suggestion
            depending on what outcome is chosen for the Sky brand, the current SKY token may be renamed (e.g., to OLD_SKY), and a new 
```

2024-10-28 14:10 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            tokenomics or anything else.<br> The 3 poll options are as follows:<br> Option 1:<br> Keep the Sky brand as
In the same spirit, it might be better to use two `<br>`

2024-10-28 14:10 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            going to happen with Sky.<br> The Accessibility Facilitator may gather feedback and input to these 3 options during
Two `<br>` from here on, I suggest

2024-10-28 14:10 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            possible.<br> Long term implications for SKY<br> If recentering the Maker brand is chosen (Option 2 or Option 3), then,
```suggestion
            possible.<br> <strong>Long term implications for SKY</strong><br> If recentering the Maker brand is chosen (Option 2 or Option 3), then, 
```

2024-10-28 14:10 UTC, blimpa commented on Sky Atlas/Sky Atlas.html
> +            to hold their original SKY tokens forever if they desire.<br> USDS core Stablecoin and DAI ERC20 Wrapper<br> The core
```suggestion
            to hold their original SKY tokens forever if they desire.<br> <strong>USDS core Stablecoin and DAI ERC20 Wrapper</strong><br> The core 
```

2024-11-03 19:54 UTC, blimpa approved these changes
Changes I suggested are only cosmetic

2024-11-03 19:57 UTC, VoteWizard approved these changes
I approve this PR and will ignore the cosmetic changes

2024-11-03 19:59 UTC, merged